{
 "title": "System Health",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Available disk space",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "15m average load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(avg by (instance, job) (node_load15)) / (count(count by (instance, job, cpu) (node_cpu_seconds_total)) by (instance, job)) * 100"
    }
   ]
  },
  {
   "title": "Web Services Responsive",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time (probe_success[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Certificate expiry",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "expr": "(probe_ssl_earliest_cert_expiry - time()) / 60.0 / 60.0 / 24.0",
     "legendFormat": "1- {{instance}}"
    }
   ]
  },
  {
   "title": "Failed backups",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"couchbackup.service\", state=\"failed\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "node_systemd_unit_state{name=\"database-dump.service\", state=\"failed\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1- (quantile_over_time(0.5, node_memory_MemAvailable_bytes[15m]) / quantile_over_time(0.5, node_memory_MemTotal_bytes[15m]))"
    }
   ]
  }
 ]
}