apiVersion: v2
name: monitoring
type: application
version: 0.1.0

dependencies:
  - name: kube-prometheus-stack
    version: 62.3.0
    repository: https://prometheus-community.github.io/helm-charts


  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 2.x.x
