apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alert-rules
  namespace: monitoring
data:
  alert-rules.yaml: |
    apiVersion: 1
    groups:
      - orgId: 1
        name: my_rule_group
        folder: my_first_folder
        interval: 60s
        rules:
          - uid: my_id_1
            title: my_first_rule
            condition: A
            data:
              - refId: A
                datasourceUid: '__expr__'
                model:
                  conditions:
                    - evaluator:
                        params:
                          - 3
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                          - A
                      reducer:
                        type: last
                      type: query
                  datasource:
                    type: __expr__
                    uid: '__expr__'
                  expression: 1==0
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: A
                  type: math
            dashboardUid: my_dashboard
            panelId: 123
            noDataState: Alerting
            execErrState: Alerting
            for: 60s
            annotations:
              some_key: some_value
            labels:
              team: sre_team_1
