{{- $files := .Files.Glob "alerting/*.yaml" -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: custom-alert-rules
  namespace: monitoring
  labels:
    prometheus: kube-prometheus-stack-prometheus
    role: alert-rules
spec:
  groups:
    - name: custom.rules
      rules:
        {{- range $path, $bytes := $files }}
        - alert: {{ $path | base | trimSuffix ".yaml" }}
          expr: {{ .Files.Get $path | toString | indent 4 }}
          labels:
            severity: critical
          annotations:
            summary: "Dynamic rule from {{ $path }}"
        {{- end }}
