apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alert-rules
  labels:
    app: grafana
    release: kube-prometheus-stack
data:
  Test-Alert.yaml: |-
    {{ .Files.Get "alerting/test.yaml" | indent 4 }}