apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-notification-policies
data:
  notification-policies.yaml: |-
    apiVersion: 1
    policies:
      - orgId: 1
        receiver: email
        provenance: kubernetes-configmap
        group_wait: 60s
        group_interval: 5m
        repeat_interval: 24h
        routes:
          - receiver: slack-channel-1
            group_wait: 60s
            group_interval: 5m
            group_by:
              - namespace
            matchers:
              - namespace =~ a|b|c|d
            repeat_interval: 5m
            continue: false
          - receiver: slack-channel-2
            group_wait: 60s
            group_interval: 5m
            group_by:
              - app
            matchers:
              - app =~ grafana|prometheus|loki
            repeat_interval: 3h
            continue: false
          - receiver: slack-channel-3
            group_wait: 60s
            group_interval: 5m
            group_by:
              - kafka-topic
            matchers:
              - namespace = kafka
              - kafka-topic =~ ^my-topic
            repeat_interval: 6h
            continue: false