{{- $files := .Files.Glob "alerting/*.yaml" -}}
{{- range $path, $bytes := $files }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: custom-alert-rules
  namespace: monitoring
  labels:
    prometheus: kube-prometheus-stack-prometheus
    role: alert-rules
spec:
  groups:
  - name: custom.rules
    rules:
    - alert: {{ $path | base | trimSuffix ".yaml" }}
      expr: |-
        {{ $bytes | toString | indent 4 }}
      labels:
        severity: critical
      annotations:
        summary: "Dynamic alert rule from {{ $path }}"
{{- end }}
