apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-contact-points
data:
  contactpoints.yaml: |-
    apiVersion: 1
    contactPoints:
      - orgId: 1
        name: cp_1
        receivers:
          - uid: first_uid
            type: telegram
            settings:
              bottoken: xxx
              chatid: some_chat_id
              message: |
                {{ template "default.message" . }}