apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-smtp-secret
  namespace: monitoring
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grafana-smtp-secret
  data:
  - secretKey: smtp-password
    remoteRef:
      key: namespaces/monitoring
      property: smtp-password