apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-notification-policies
  namespace: monitoring
data:
  notificationpolicy.yaml: |-
    apiVersion: 1
    policies:
        - orgId: 1
          receiver: grafana-default-email
          group_by:
            - grafana_folder
            - alertname
