apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-notification-policies
  namespace: monitoring
data:
  notificationpolicy.yaml: |-
    apiVersion: 1
    policies:
      - orgId: 1
        receiver: grafana-default-email
        group_by: ['...']
        matchers:
          - alertname = Watchdog
          - service_id_X = serviceX
          - severity =~ "warning|critical"
        object_matchers:
          - ['alertname', '=', 'CPUUsage']
          - ['service_id-X', '=', 'serviceX']
          - ['severity', '=~', 'warning|critical']
        mute_time_intervals:
          - abc
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 4h