apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-notification-policies
  namespace: monitoring
data:
  notificationpolicies.yaml: |-
    {{ (.Files.Get "provisioning/alerting/notificationpolicies.yaml") | nindent 4 }}