apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-templates
  namespace: monitoring
data:
  templates.yaml: |-
    apiVersion: 1
    templates:
      - orgId: 1
        name: my_first_template
        template: |
          {{- define "default.message" -}}
          Default alert message
          {{- end -}}