apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/samskrutha/cluster-services'  
    targetRevision: HEAD
    path: services/monitoring
    helm:
      valuesObject:
        grafana:
          enabled: true
          nodeExporter:
            enabled: false
          grafana:
            alerting:
              enabled: true  
        alertmanager:
          alertmanagerSpec:
            replicas: 1 
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
