{{if .Values.kubePrometheusStack.enabled}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/samskrutha/cluster-services'  
    targetRevision: HEAD
    path: services/monitoring  
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  sources:
      helm:
        valuesObject:
          grafana:
            enabled: true
            nodeExporter:
              enabled: false
            sidecar:
              alerts:
                enabled: true
                label: grafana_alert

