apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-alerts
  namespace: monitoring
spec:
  groups:
    - name: Test Alerts
      rules:
        - alert: TestAlert
          expr: aggregator_discovery_aggregation_count_total{namespace="kube-system"}
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Test Alert Triggered"
