kubePrometheusStack:
  enabled: true
  version: 62.3.0
  values:
    grafana_enabled: true
    thanosIngress_enabled: false
    nodeExporter:
      enabled: false
    grafana:
      alerting:
        enabled: true
      extraConfigmapMounts:
        - name: grafana-alert-rules
          mountPath: /etc/grafana/provisioning/alerting
          configMap: grafana-alert-rules