kubePrometheusStack:
  enabled: true
  version: 62.3.0
  values:
    grafana_enabled: true
    thanosIngress_enabled: false
    nodeExporter:
      enabled: false
    grafana:
      alerting:
        enabled: true
        label: grafana_alerts   